install: use frozen plugin versions for Jenkins 2.249.3
Freeze the versions of plugins used with Jenkins server version 2.249.3
As the plugin versions drift over time, it causes all kinds of problems.

I think this will solve the 'ftc add-nodes' problem where it returns
this error:
ERROR: Operation 'add-nodes' raised exception with string:
Error in request. Possibly authentication failed [500]: Server Error

Signed-off-by: Tim Bird <tim.bird@sony.com>